version: '3.9'
services:
  server:
    build: ./server
    ports:
      - "5001:5001"
    volumes:
      - ./server:/app
    restart: always

  client:
    build: ./client
    ports:
      - "3000:80"
    volumes:
      - ./client:/app
    restart: always
